name: Auto Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint on frontend
        working-directory: ./frontend
        run: npx eslint . --config eslint.config.js

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run ESLint on backend
        working-directory: ./backend
        run: npx eslint . --config eslint.config.js
